#ifndef CONSTANTES_H
#define CONSTANTES_H

#endif // CONSTANTES_H

#define PLANTILLA_ARBITROS_COL_DORSAL 1
#define PLANTILLA_ARBITROS_COL_NOMBRE 2
#define PLANTILLA_ARBITROS_COL_SEXO 3
#define PLANTILLA_ARBITROS_COL_FECHA_NACIMIENTO 4
#define PLANTILLA_ARBITROS_COL_CATEGORIA 5
#define PLANTILLA_ARBITROS_COL_COMARCA 6
#define PLANTILLA_ARBITROS_FILA_INICIO 3

#define PLANTILLA_BONUS_COL_INICIO 2
#define PLANTILLA_BONUS_FILA_INICIO 3

#define PLANTILLA_RESULTADOS_DORSAL 2
#define PLANTILLA_RESULTADOS_NOMBRE 3
#define PLANTILLA_RESULTADOS_C6x40 4
#define PLANTILLA_RESULTADOS_PROMEDIO_C6x40 11
#define PLANTILLA_RESULTADOS_BONIFICACION_C6x40 12
#define PLANTILLA_RESULTADOS_C2000 13
#define PLANTILLA_RESULTADOS_BONIFICACION_C2000 14
#define PLANTILLA_RESULTADOS_CPC 15
#define PLANTILLA_RESULTADOS_BONIFICACION_CPC 16
#define PLANTILLA_RESULTADOS_TOTAL_BONIFICACION 17


